apiVersion: v1
kind: Service
metadata:
  name: training-portal
  namespace: itc-training
  labels:
    app: training-portal
spec:
  type: NodePort
  selector:
    app: training-portal
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30300
