apiVersion: v1
kind: Service
metadata:
  name: lab-proxy
  namespace: itc-training
  labels:
    app: lab-proxy
spec:
  type: NodePort
  selector:
    app: lab-proxy
  ports:
    - name: yarn-ui
      port: 8088
      targetPort: 8088
      nodePort: 30088
    - name: hdfs-ui
      port: 9870
      targetPort: 9870
      nodePort: 30870
    - name: spark-ui
      port: 18088
      targetPort: 18088
      nodePort: 31088
    - name: cloudera-manager
      port: 7180
      targetPort: 7180
      nodePort: 31780
    - name: hue
      port: 8889
      targetPort: 8889
      nodePort: 30889
