pipeline {
    agent any
    environment {
        VENV_DIR = 'venv'
        DOCKER_IMAGE = 'rdv100/predict_fraud:2.8'
        KUBECONFIG = credentials('kubeconfig-file')
        KUBE_NAMESPACE  = 'default'
    }
    stages{
        stage("Clone Repository"){
            steps{
                git url: 'https://github.com/uttamraj9/Big_Data_Project.git', branch: 'feature/ml-predict'
            }
        }
        stage('Build Docker Image') {
            steps{
                script{
                    sh 'docker build -t ${DOCKER_IMAGE} -f ml/predict/Dockerfile ml/predict'
                }
            }
        }
        stage("Push Docker Imae to Docker Hub"){
            steps{
                script{
                    // Login to Docker hub
                    withCredentials([usernamePassword(credentialsId: 'rdv-hub', usernameVariable: 'RDV_DKR_HUB_USERNAME', passwordVariable: 'RDV_DKR_HUB_PASSWORD')]) {
                        sh 'echo ${RDV_DKR_HUB_PASSWORD} | docker login -u ${RDV_DKR_HUB_USERNAME} --password-stdin'
                    }
                    // Push the image there
                    sh 'docker push ${DOCKER_IMAGE}'
                }
            }
        }
        stage("Verify Deployment Files"){
            steps{
                script{
                    sh 'ls -al ml/predict'
                }
            }
        }
        stage("Deploy to Kubernetes"){
            steps{
                script{
                    sh 'kubectl delete cronjob fraud-predict-cron --ignore-not-found'
                    sh 'kubectl apply -f ml/predict/predict-cron.yaml'
                }
            }
        }
    }
    post{
        success{
            echo 'Build Success. Prediction Cron job launched successfully.'
        }
    }
}
